JWT + 구글 OAuth2 기능 추가
apeun-gidaechi/seugi-server pull request #6
Opened 2024-03-26 23:45 UTC by seu1a

#2 

🐳 한 일
- 로그인 & 회원가입
- JWT 발급, 구글 OAuth2

🙏 할 일
- 채팅 기능과 연동
- 이메일 인증 기능
- 스페이스 기능
- 애플 OAuth2 <- Apple Developer 계정 필요

2024-03-26 23:56 UTC, yeseong0412 requested changes
코멘트 남긴거 읽고 수정하고 머지하면 될것 같아요

2024-03-26 23:56 UTC, yeseong0412 commented on src/main/kotlin/seugi/server/domain/member/adapter/in/controller/LoginMemberController.kt
> +@RequestMapping("member")
이거랑 아래 PostMapping 부분에 / 안해도 상관없는데 하는게 가독성 부분에서 좋아요

2024-03-26 23:56 UTC, yeseong0412 commented on src/main/kotlin/seugi/server/domain/member/application/service/RegisterMemberService.kt
> +            return BaseResponse (
이거 응답값으로 보내지 않고 Custom Exception 활용하면 좋은데 나중에 코드 첨부함

2024-03-26 23:56 UTC, yeseong0412 commented on src/main/kotlin/seugi/server/global/auth/oauth/OAuth2MemberService.kt
> +@Component
@Component , @Service 어노테이션 차이는 없는데 관점적으로 service 사용하는게 가독성 부분에서 좋음 (명시적활용도)

2024-03-26 23:56 UTC, yeseong0412 commented on src/main/kotlin/seugi/server/global/auth/oauth/OAuth2MemberService.kt
> +@Component
사비스라고 되있음 @service 사용하는게 좋아요

2024-03-26 23:56 UTC, yeseong0412 commented on src/main/kotlin/seugi/server/domain/member/application/service/RegisterMemberService.kt
> +            return BaseResponse (
https://velog.io/@hwsa1004/Spring-%EC%98%88%EC%99%B8%EC%B2%98%EB%A6%ACCustom-Exception-%EB%A7%8C%EB%93%A4%EA%B8%B0

참고하면 좋음

2024-03-27 00:00 UTC, yeseong0412 commented on src/main/kotlin/seugi/server/domain/member/application/service/RegisterMemberService.kt
> +            return BaseResponse (
https://velog.io/@rungoat/SpringBoot-Custom-Exception-%EC%B2%98%EB%A6%AC

2024-03-27 00:00 UTC, yeseong0412 commented on src/main/kotlin/seugi/server/domain/member/application/service/RegisterMemberService.kt
> +            return BaseResponse (
Custom Exception 키워드로 검색 ㄱㄱ

2024-03-27 05:44 UTC, seu1a commented on src/main/kotlin/seugi/server/global/auth/oauth/OAuth2MemberService.kt
> +@Component
넵 감사합니다! ☺️

2024-03-27 05:45 UTC, seu1a commented on src/main/kotlin/seugi/server/domain/member/adapter/in/controller/LoginMemberController.kt
> +@RequestMapping("member")
넵 슬래시로 수정하겠습니다 👍 👍

2024-03-27 11:07 UTC, seu1a commented on src/main/kotlin/seugi/server/domain/member/application/service/RegisterMemberService.kt
> +            return BaseResponse (
감사합니다. 반영하도록 수정했습니다 👍
CustomErrorCode를 도메인별로 나누어 관리하는게 어떨까요 ?
Global 패키지에서 모두 관리하기엔 유지보수에 어려움이 생길 것 같습니다 !!

2024-03-27 11:47 UTC, yeseong0412 reviewed
좋습니다

2024-03-27 11:47 UTC, yeseong0412 approved these changes

2024-03-27 11:48 UTC, yeseong0412 commented on src/main/kotlin/seugi/server/domain/member/application/service/RegisterMemberService.kt
> +            return BaseResponse (
심자때 잠시 만나서 제가 코드 공유해드릴게요

2024-03-27 11:48 UTC, merged